CREATE TABLE `test_table` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(45) DEFAULT NULL,
  `SEX` tinyint(4) DEFAULT NULL,
  `BIRTH_DATE` datetime DEFAULT NULL,
  `DESCRIPTION` text,
  `LOGIN_TIMES` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=37 DEFAULT CHARSET=utf8;
